@ToromontFleetHub.Api_HostAddress = http://localhost:5045

#if (EnableOpenAPI)
GET {{ToromontFleetHub.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###
#endif

GET {{ToromontFleetHub.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
